from abaqus import *
from abaqusConstants import *
s = mdb.models['Model-1'].ConstrainedSketch(name='__profile__', sheetSize=10.0)
s.rectangle(point1=(0.000000, 0.000000), point2=(1000.000000, 500.000000))
p = mdb.models['Model-1'].Part(name='Part-1',dimensionality=TWO_D_PLANAR,type=DEFORMABLE_BODY) 
p.BaseShell(sketch=s)
s0 = mdb.models['Model-1'].ConstrainedSketch(name='__profile__',sheetSize=200.0)
g, v, d, c = s0.geometry, s0.vertices, s0.dimensions, s0.constraints
s0.Line(point1=(212.000000, 313.000000), point2=(233.000000, 290.000000))
s0.Line(point1=(233.000000, 290.000000), point2=(241.000000, 264.000000))
s0.Line(point1=(241.000000, 264.000000), point2=(239.000000, 231.000000))
s0.Line(point1=(239.000000, 231.000000), point2=(227.000000, 206.000000))
s0.Line(point1=(227.000000, 206.000000), point2=(209.000000, 189.000000))
s0.Line(point1=(209.000000, 189.000000), point2=(187.000000, 179.000000))
s0.Line(point1=(187.000000, 179.000000), point2=(172.000000, 176.000000))
s0.Line(point1=(172.000000, 176.000000), point2=(117.000000, 176.000000))
s0.Line(point1=(117.000000, 176.000000), point2=(117.000000, 327.000000))
s0.Line(point1=(117.000000, 327.000000), point2=(175.000000, 327.000000))
s0.Line(point1=(175.000000, 327.000000), point2=(195.000000, 322.000000))
s0.Line(point1=(195.000000, 322.000000), point2=(212.000000, 313.000000))
s0.Line(point1=(137.000000, 310.000000), point2=(166.000000, 310.000000))
s0.Line(point1=(166.000000, 310.000000), point2=(189.000000, 305.000000))
s0.Line(point1=(189.000000, 305.000000), point2=(204.000000, 296.000000))
s0.Line(point1=(204.000000, 296.000000), point2=(216.000000, 279.000000))
s0.Line(point1=(216.000000, 279.000000), point2=(220.000000, 263.000000))
s0.Line(point1=(220.000000, 263.000000), point2=(217.000000, 229.000000))
s0.Line(point1=(217.000000, 229.000000), point2=(209.000000, 214.000000))
s0.Line(point1=(209.000000, 214.000000), point2=(188.000000, 198.000000))
s0.Line(point1=(188.000000, 198.000000), point2=(161.000000, 193.000000))
s0.Line(point1=(161.000000, 193.000000), point2=(137.000000, 194.000000))
s0.Line(point1=(137.000000, 194.000000), point2=(137.000000, 310.000000))
s0.Line(point1=(269.000000, 327.000000), point2=(289.000000, 327.000000))
s0.Line(point1=(289.000000, 327.000000), point2=(289.000000, 176.000000))
s0.Line(point1=(289.000000, 176.000000), point2=(269.000000, 176.000000))
s0.Line(point1=(269.000000, 176.000000), point2=(269.000000, 327.000000))
s0.Line(point1=(439.000000, 323.000000), point2=(440.000000, 301.000000))
s0.Line(point1=(440.000000, 301.000000), point2=(407.000000, 312.000000))
s0.Line(point1=(407.000000, 312.000000), point2=(381.000000, 311.000000))
s0.Line(point1=(381.000000, 311.000000), point2=(362.000000, 302.000000))
s0.Line(point1=(362.000000, 302.000000), point2=(352.000000, 292.000000))
s0.Line(point1=(352.000000, 292.000000), point2=(344.000000, 278.000000))
s0.Line(point1=(344.000000, 278.000000), point2=(340.000000, 263.000000))
s0.Line(point1=(340.000000, 263.000000), point2=(340.000000, 238.000000))
s0.Line(point1=(340.000000, 238.000000), point2=(350.000000, 211.000000))
s0.Line(point1=(350.000000, 211.000000), point2=(364.000000, 198.000000))
s0.Line(point1=(364.000000, 198.000000), point2=(386.000000, 191.000000))
s0.Line(point1=(386.000000, 191.000000), point2=(409.000000, 192.000000))
s0.Line(point1=(409.000000, 192.000000), point2=(423.000000, 197.000000))
s0.Line(point1=(423.000000, 197.000000), point2=(423.000000, 238.000000))
s0.Line(point1=(423.000000, 238.000000), point2=(390.000000, 238.000000))
s0.Line(point1=(390.000000, 238.000000), point2=(390.000000, 255.000000))
s0.Line(point1=(390.000000, 255.000000), point2=(443.000000, 256.000000))
s0.Line(point1=(443.000000, 256.000000), point2=(443.000000, 186.000000))
s0.Line(point1=(443.000000, 186.000000), point2=(426.000000, 178.000000))
s0.Line(point1=(426.000000, 178.000000), point2=(399.000000, 173.000000))
s0.Line(point1=(399.000000, 173.000000), point2=(372.000000, 175.000000))
s0.Line(point1=(372.000000, 175.000000), point2=(350.000000, 184.000000))
s0.Line(point1=(350.000000, 184.000000), point2=(329.000000, 206.000000))
s0.Line(point1=(329.000000, 206.000000), point2=(319.000000, 235.000000))
s0.Line(point1=(319.000000, 235.000000), point2=(319.000000, 264.000000))
s0.Line(point1=(319.000000, 264.000000), point2=(329.000000, 293.000000))
s0.Line(point1=(329.000000, 293.000000), point2=(346.000000, 313.000000))
s0.Line(point1=(346.000000, 313.000000), point2=(372.000000, 327.000000))
s0.Line(point1=(372.000000, 327.000000), point2=(410.000000, 330.000000))
s0.Line(point1=(410.000000, 330.000000), point2=(439.000000, 323.000000))
s0.Line(point1=(477.000000, 327.000000), point2=(497.000000, 327.000000))
s0.Line(point1=(497.000000, 327.000000), point2=(497.000000, 176.000000))
s0.Line(point1=(497.000000, 176.000000), point2=(477.000000, 176.000000))
s0.Line(point1=(477.000000, 176.000000), point2=(477.000000, 327.000000))
s0.Line(point1=(616.000000, 325.000000), point2=(616.000000, 303.000000))
s0.Line(point1=(616.000000, 303.000000), point2=(593.000000, 312.000000))
s0.Line(point1=(593.000000, 312.000000), point2=(567.000000, 311.000000))
s0.Line(point1=(567.000000, 311.000000), point2=(553.000000, 301.000000))
s0.Line(point1=(553.000000, 301.000000), point2=(551.000000, 284.000000))
s0.Line(point1=(551.000000, 284.000000), point2=(560.000000, 272.000000))
s0.Line(point1=(560.000000, 272.000000), point2=(597.000000, 253.000000))
s0.Line(point1=(597.000000, 253.000000), point2=(616.000000, 237.000000))
s0.Line(point1=(616.000000, 237.000000), point2=(623.000000, 220.000000))
s0.Line(point1=(623.000000, 220.000000), point2=(622.000000, 203.000000))
s0.Line(point1=(622.000000, 203.000000), point2=(617.000000, 192.000000))
s0.Line(point1=(617.000000, 192.000000), point2=(603.000000, 180.000000))
s0.Line(point1=(603.000000, 180.000000), point2=(584.000000, 174.000000))
s0.Line(point1=(584.000000, 174.000000), point2=(554.000000, 174.000000))
s0.Line(point1=(554.000000, 174.000000), point2=(530.000000, 181.000000))
s0.Line(point1=(530.000000, 181.000000), point2=(529.000000, 204.000000))
s0.Line(point1=(529.000000, 204.000000), point2=(548.000000, 194.000000))
s0.Line(point1=(548.000000, 194.000000), point2=(581.000000, 191.000000))
s0.Line(point1=(581.000000, 191.000000), point2=(597.000000, 198.000000))
s0.Line(point1=(597.000000, 198.000000), point2=(602.000000, 209.000000))
s0.Line(point1=(602.000000, 209.000000), point2=(601.000000, 221.000000))
s0.Line(point1=(601.000000, 221.000000), point2=(592.000000, 232.000000))
s0.Line(point1=(592.000000, 232.000000), point2=(555.000000, 251.000000))
s0.Line(point1=(555.000000, 251.000000), point2=(535.000000, 268.000000))
s0.Line(point1=(535.000000, 268.000000), point2=(530.000000, 280.000000))
s0.Line(point1=(530.000000, 280.000000), point2=(530.000000, 295.000000))
s0.Line(point1=(530.000000, 295.000000), point2=(535.000000, 310.000000))
s0.Line(point1=(535.000000, 310.000000), point2=(550.000000, 323.000000))
s0.Line(point1=(550.000000, 323.000000), point2=(567.000000, 329.000000))
s0.Line(point1=(567.000000, 329.000000), point2=(596.000000, 330.000000))
s0.Line(point1=(596.000000, 330.000000), point2=(616.000000, 325.000000))
s0.Line(point1=(651.000000, 327.000000), point2=(671.000000, 327.000000))
s0.Line(point1=(671.000000, 327.000000), point2=(671.000000, 176.000000))
s0.Line(point1=(671.000000, 176.000000), point2=(651.000000, 176.000000))
s0.Line(point1=(651.000000, 176.000000), point2=(651.000000, 327.000000))
s0.Line(point1=(710.000000, 327.000000), point2=(738.000000, 327.000000))
s0.Line(point1=(738.000000, 327.000000), point2=(788.000000, 206.000000))
s0.Line(point1=(788.000000, 206.000000), point2=(841.000000, 327.000000))
s0.Line(point1=(841.000000, 327.000000), point2=(867.000000, 327.000000))
s0.Line(point1=(867.000000, 327.000000), point2=(867.000000, 176.000000))
s0.Line(point1=(867.000000, 176.000000), point2=(847.000000, 176.000000))
s0.Line(point1=(847.000000, 176.000000), point2=(848.000000, 301.000000))
s0.Line(point1=(848.000000, 301.000000), point2=(795.000000, 177.000000))
s0.Line(point1=(795.000000, 177.000000), point2=(783.000000, 176.000000))
s0.Line(point1=(783.000000, 176.000000), point2=(735.000000, 284.000000))
s0.Line(point1=(735.000000, 284.000000), point2=(730.000000, 302.000000))
s0.Line(point1=(730.000000, 302.000000), point2=(730.000000, 176.000000))
s0.Line(point1=(730.000000, 176.000000), point2=(710.000000, 176.000000))
s0.Line(point1=(710.000000, 176.000000), point2=(710.000000, 327.000000))
p1 = mdb.models['Model-1'].parts['Part-1']
pickedFaces = p1.faces[0:1]
p1.PartitionFaceBySketch(faces=pickedFaces, sketch=s0)
f2=mdb.models['Model-1'].parts['Part-1'].faces
for i in range(len(f2)):
  mdb.models['Model-1'].parts['Part-1'].Set(name = 'Set'+str(i) , faces=f2[i:i+1])
